FROM php:7.3-apache
MAINTAINER Maarten van der Peet <Maarten.van.der.Peet@di.huc.knaw.nl>
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf && a2enmod rewrite
# https://stackoverflow.com/questions/48868357/docker-php-apache-container-set-the-servername-directive-globally?rq=1

